### ISSUE TITLE
Basic implementation

### ISSUE THREAD

**Issue by sapegin** [webpack-contrib/webpack-defaults#1]
- [x] Sync using [mrm](https://github.com/sapegin/mrm-core)
- [x] `.gitignore`
- [x] `.editorconfig`
- [x] ESLint
- [x] Babel
- [x] Jest
- [x] GitHub templates: issue, PR
- [x] [lint-staged](https://github.com/okonet/lint-staged)
- [x] Basic readme template
- [x] License
- [x] Changelog
- [x] Publish to npm

Postponed / cancelled:

- [conventional-changelog-lint](https://github.com/marionebl/conventional-changelog-lint)

**Comment by bebraw** [comment]
Might as well publish 0.0.1 or 0.1.0.

**Comment by sapegin** [comment]
Would be nice because I don’t know what else I can do here and would like to have some feedback.

**Comment by bebraw** [comment]
Ok, feel free. We can add owners to the package as needed.

**Comment by sapegin** [comment]
webpack-defaults@0.0.1 is on npm now!
