### ISSUE TITLE
Installing webpack-defaults should write webpack-defaults script to run?

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/webpack-defaults#11]
If you use webpack-defaults, you have to write the script anyhow so maybe it makes sense to write `"webpack-defaults": "webpack-defaults"` to `scripts`.

Any thoughts?

**Comment by sapegin** [comment]
You mean `postinstall` or something?

**Comment by bebraw** [comment]
Yeah. I'm thinking writing that script on `postinstall` would be the key.

**Comment by sapegin** [comment]
Could you make a PR for that? I haven’t seen the latest version of your script yet ;-)

**Comment by bebraw** [comment]
Yeah, I'll give it some thought. I guess the problem is figuring out a good way to detect the context (user installed the first time).

**Comment by sapegin** [comment]
Why do you need to detect it? If the script isn’t in the `package.json`, than it wasn’t installed before.

**Comment by bebraw** [comment]
Yeah, great point. Easy enough. 👍
