### ISSUE TITLE
Problem in webpack.js.org

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/webpack-defaults#112]
Looks on https://webpack.js.org/loaders/raw-loader/ 

On top:
```
[![npm][npm]][npm-url] [![node][node]][node-url] [![deps][deps]][deps-url] [![tests][tests]][tests-url] [![chat][chat]][chat-url]
```

Original PR with description: https://github.com/webpack-contrib/raw-loader/pull/52

Maybe should be fixed in https://github.com/webpack/webpack.js.org

**Comment by michael-ciniawsky** [comment]
We should restore the old README boilerplate which was triaged and supported by the docs team back in the days, but I also think there where changes made to the site, which broke some markdown features (rendering) in general

cc @montogeek @Munter

**Comment by michael-ciniawsky** [comment]
#73 as a follow up

**Comment by montogeek** [comment]
I will take a look

**Comment by montogeek** [comment]
@evilebottnawi It used to work before? Issue is that marked (MD parser used by website) doesn't support footnotes links.

**Comment by montogeek** [comment]
Good news, this is fixed in the website version that we hope we could deploy soon.

**Comment by montogeek** [comment]
@michael-ciniawsky Source code: https://github.com/webpack/webpack.js.org/blob/master/src/utilities/markdown.js

**Comment by Munter** [comment]
I can confirm this will be fixed when #2039 merges

**Comment by montogeek** [comment]
Yes, new website isn't done

**Comment by evilebottnawi** [comment]
Solved
