### ISSUE TITLE
Allow Jest expect as global in ESLint?

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/webpack-defaults#12]
If you use Jest assertions for testing, you likely want to allow `expect` as a global. That might be a good default. Did we specify earlier how to assert?

**Comment by sapegin** [comment]
We can add a `jest` environment to ESLint.

**Comment by bebraw** [comment]
Yeah, that will probably do it. Let me move this to the right place.

**Comment by d3viant0ne** [comment]
`eslint-config-webpack v1.1.0` is out on npm. Along with a few other tweaks, it adds Jest to the env object which covers all of the Jest globals.
