### ISSUE TITLE
Structure of tests

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/webpack-defaults#131]
# Flatten (doesn't grouping same test in directory)
```
test
|– ...
|– Errors.test.js
|– loader.test.js (Plugin.test.js)
|– x-option.test.js
|– ...
```

# Nested (grouping same test in directory)
```
test
|– Errors.test.js
|– loader.test.js (Plugin.test.js)
|
|– options
||– x.test.js
||–  ...
```

Also i propose rename `Error.test.js` to `validation.test.js` (because real tests with errors should be handle inside `loader/Plugin` and per options file to better searching test file, also plugin/loader can have a lot of test on errors and it is bad contain their in one file).

**Comment by michael-ciniawsky** [comment]
Yes someone should mediate here, it was obvious that this would happen :). Maybe I would be fine with

```
test
|– validation.test.js (Schema)
|– defaults.test.js (Loader/Plugin)
| // Options
|– include.test.js // for e.g
|– exclude.test.js // for e.g
```

**Comment by evilebottnawi** [comment]
@michael-ciniawsky you can have `include.js` file and `include` option, it is why your structure is mesleading

**Comment by michael-ciniawsky** [comment]
I don't understand, please try to rephrase

**Comment by evilebottnawi** [comment]
@michael-ciniawsky Theoretically structure:
```
src
|– index.js (Loader/Plugin)
|– include.js
|– include
|| – index.js
|| – action.js
```

What is structure of tests for your purpose?

My solution is put `*.test.js` file where original file placed in `src` and flat `options/feature/etc` tests in same directory.

```
test
|– validation.test.js (Options Schema)
|– defaults.test.js (Loader/Plugin)
|– include-options.test.js
|– include.test.js 
|– include
||– index.test.js
||– action.test.js 
```

I used this structure a lot of years for `php/js/ruby` projects and no problem, your structure really misleading.

**Comment by michael-ciniawsky** [comment]
Ok :) then someone needs to mediate here as I'm definitely disagreeing with matching `src` and `test` by default

**Comment by evilebottnawi** [comment]
Opt for flatten tests, nested test files should be created for nested directories:
- `index.js` -> `test/index.test.js`
- `nested/utils.js` -> `test/nested/utils.test.js`
