### ISSUE TITLE
Defaults merges .babelrc content

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/webpack-defaults#21]
- If a babelrc file exists, defaults will merge the old with the new. That is going to have side effects for repos that already use some level of babel.

**Comment by sapegin** [comment]
That’s the basic idea of mrm: make less destructive update and allow customizations. It’s possible to overwrite file as well, I can do it.

**Comment by d3viant0ne** [comment]
For the babelrc, overwrite is the only way it's going to work.

defaults output + other plugins will fail given they aren't installed.
