### ISSUE TITLE
Defaults should override license?

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/webpack-defaults#25]
Since the assumption is that these are JS Foundation projects, **package.json** `"license": "MIT",` should be set, right? Looks like it doesn't override an empty field.

**Comment by sapegin** [comment]
It doesn’t right anything to `license` field now. Easy to change.

**Comment by bebraw** [comment]
Ok. Given we are on JSF, it should follow their default. 👍

**Comment by sapegin** [comment]
MIT is good for JSF?

**Comment by bebraw** [comment]
Yeah, that's basically what all **webpack-contrib** projects should use I think.

Let's wait a confirmation from @d3viant0ne before making any moves, though. I remember seeing some mentions about Apache license with a patent clause, but I'm not sure how strict they are about that.

**Comment by d3viant0ne** [comment]
JSF Is not a valid SPDX License definition & it will throw a warning on install. 

See: https://spdx.org/licenses/

This is really a question we should really ask @kborchers as I only know enough about software licensing to be dangerous, never a good thing with legal matters.

@kborchers - In summary, a NodeJS `package.json` has a `license` field that expects a valid `SPDX` license definition. Currently the JSF License is in place in all of the libraries in the organization and published to npm with the source code. 

We could use some advice on how to handle the `license` field in the `package.json`.

**Comment by sapegin** [comment]
It [should be](https://docs.npmjs.com/files/package.json#license) `SEE LICENSE IN <LICENSE>` as I understand.

**Comment by d3viant0ne** [comment]
Love those `RTFM Josh` moments. Yeah, that's probably the right answer

**Comment by kborchers** [comment]
It should be the actual license so `Apache-2.0` for example.

That said, our IP policy defaults to Apache 2.0. If a project coming in is not Apache 2.0, it either needs to re-license or there needs to a be approval from legal to use a different license like MIT, BSD, what ever. In general, as long as these webpack-contrib projects are using Apache 2.0, MIT or BSD they will likely get a quick approval but that review needs to happen. Please ping legal@js.foundation with the alternative license request and a link to the project in question before transferring it into the webpack-contrib org going forward.

If any of these projects currently in the webpack or webpack-contrib orgs have a license other than those 3, please let me know ASAP as that will need to be corrected immediately with legal's guidance.

**Comment by kborchers** [comment]
BTW, I just looked at awesome-webpack which is CC0 which is fine for a list of links so no need to inform me about that one.

**Comment by d3viant0ne** [comment]
Everything in the org has the JSF `LICENSE` & `MIT` in the package.json.

**Comment by kborchers** [comment]
I will have legal do blanket review of what is here. The main reason for defaulting to Apache is around patents which are not covered by MIT/BSD licenses so if there are any patent concerns, unlikely IMO, those projects may be asked to re-license but otherwise having the appropriate LICENSE file and MIT in package.json should be good for everything currently in this org. We will still need notification going forward when a project is coming in with something other than Apache 2.0.

**Comment by d3viant0ne** [comment]
That sounds as fun as a tax audit :)

Thanks for the quick response, again.

**Comment by bebraw** [comment]
Is it enough if the author of a project we might add below **webpack-contrib** agrees to re-license under Apache 2.0 upon move?

**Comment by d3viant0ne** [comment]
I'll take it up with the legal folks and run the entire approval / transfer process past them.

**Comment by kborchers** [comment]
@bebraw yes, if a project re-licenses to Apache 2.0 or is already Apache 2.0, they are likely good to move in. In the re-license case, it's still worth a note to legal before the move if they aren't already using a license or have a license but aren't using MIT or BSD already to ensure compatibility when re-licensing as some licenses may not allow that re-license so we don't want a project to get into that mess either.

**Comment by d3viant0ne** [comment]
@kborchers - In the spirit of saving the legal folks some time, this was the compliance pass to get the CLA Assistant enabled a few weeks ago.

Issue: https://github.com/webpack-contrib/organization/issues/4

Copyright Transfers: https://github.com/webpack-contrib/organization/issues/4#issuecomment-281312213

Anything with `COPYRIGHT TRANSFER` was a library that was `signed over` and has a link to the pull request along with the username of the original copyright holder. All transfers were committed by the original copyright holder.

License Type Listing: https://github.com/webpack-contrib/organization/issues/4#issuecomment-284935502

Notably, there are two libraries that are licensed as `ISC` which from reading above we will require guidance on.

Everything else in the organization ( less awesome-webpack ) is and has been licensed as `MIT` which we can re-license to `Apache 2.0` if instructed to do so by the legal folks.

**Comment by d3viant0ne** [comment]
Closing this as the answer was a resounding no on the legal side.
