### ISSUE TITLE
When creating a new project, we should add webpack-contrib owners to npm package

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/webpack-defaults#26]
It would probably make sense to publish `0.0.0` or `0.0.1` if we set up new projects and associate webpack-contrib owners with it. This way we avoid npm issues (single owner). I'm not sure if **webpack-defaults** is the right place for this issue, but it has to be tracked somewhere so.

**Comment by d3viant0ne** [comment]
We could possible do it in the `contrib-sync` tool though I tend to think of automation as "needing to be faster than manual execution".

Personally, I think we should just create proper groups in NPM assign the proper people and then assign a single group to the lib. This also has the benefit of simplifying the process of removing an individual's NPM publish rights without having to do it on a library by library basis which is tedious and error prone.

**Comment by bebraw** [comment]
Yeah, I thought npm groups are for organizations (paid feature) only, but if it's possible to set them up, go for it. A lot easier to assign and manage a group than the alternative.

**Comment by d3viant0ne** [comment]
We have time now and realistically, this is something else where the process should be defined & then bounced off the JSF Legal department just to be sure before anything moves.

**Comment by michael-ciniawsky** [comment]
`webpack-contrib-bot` (Shared Account) ? e.g [eslint-bot](https://github.com/eslint-bot), [electron-bot](https://github.com/electron-bot)?

**Comment by d3viant0ne** [comment]
kind of a point of contention at the moment, also something that can't even be properly planned until we have solidified the long list of processes we are still working on documenting.

Automation is an end game, not an answer to the "how"

**Comment by michael-ciniawsky** [comment]
I think npm ownership should be manually handled/checked/verified by you both, a repo transfer doesn't happen that often, so automation isn't really needed for this :)
