### ISSUE TITLE
When syncing a project, update readme based on metadata too?

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/webpack-defaults#28]
In order to guarantee high quality **package.json** metadata and to decrease the possibility for mistakes, it would make sense to derive as much of **README.md** based on it as possible. This means filling in fields like project description, maintainers, and possible a few others.

**Comment by sapegin** [comment]
That’s great idea. But I’m not sure how to solve it. Maybe mark user parts with some comment?

```
<!-- text -->

This will survive updates.

<!-- /text -->
```

**Comment by michael-ciniawsky** [comment]
remark + plugins (JSDoc (Usage, Options, Examples), package.json (Metadata))

README.md.template/README.md => Remark => README.md

?

**Comment by sapegin** [comment]
I’m not sure it could (and should) be 100% autogenerated.

**Comment by bebraw** [comment]
Comments would be the way. You would have to name and detect them. That feels like a remark plugin.

**Comment by bebraw** [comment]
Not all should be autogenerated. You will still have to write intro and documentation. The middle part of a readme is freeform pretty much.

**Comment by d3viant0ne** [comment]
Essentially, just spit out what already exists in Michael's template and fill in the name / badge urls / description.

**Comment by sapegin** [comment]
How about something like this? They have more stuff which we probably don’t need.

Maybe I’ll just add support for Markdown templates to mrm-core.

**Comment by bebraw** [comment]
Yeah, **markdown-magic** fits it.

**Comment by bebraw** [comment]
Essentially we would write a custom transform to capture the data from **package.json**. That would solve it.

**Comment by sapegin** [comment]
You’ll need to put this data to Readme somehow anyway ;-)

**Comment by bebraw** [comment]
Yup. Less to maintain with a transform in place.
