### ISSUE TITLE
RELEASE: Add a note/guide about the release process

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/webpack-defaults#29]
Currently many folks bump the version in `package.json` when submitting a PR, this is undisred behaviour since it's the repective maintainers job to do that and not all PR's result in a release

We need to add a note to the  `PR_TEMPLATE` to **not**  bump versions on your own when suubmitting a PR :)

**Comment by bebraw** [comment]
Could we set up a rule (something like ESLint, but against **package.json**) so the CI will fail in this case?

**Comment by sapegin** [comment]
I believe Danger.js can do that. But setup must be more complicated than ESLint.

**Comment by bebraw** [comment]
Since versions are tagged, maybe the quickest solution would be to write a tiny script to check **package.json** version against git tags. If the version isn't there, it has been modified. There are other solutions too (comparing against `master` version etc.).

**Comment by d3viant0ne** [comment]
This problem isn't prolific enough to need some sort of automation to detect a package bump in a PR.

**Comment by d3viant0ne** [comment]
99.8% of people know better

**Comment by bebraw** [comment]
Ok, template it is. 👍

**Comment by d3viant0ne** [comment]
We already have a rather extensive doc on the release process

**Comment by sapegin** [comment]
Then we probably should link them in a PR template?

**Comment by d3viant0ne** [comment]
Releasing is a maintenance task. Bumping the version in a pull request is ... I have no nice way to explain why that happens. We can just leave it at "it doesn't happen often"

**Comment by michael-ciniawsky** [comment]
> Releasing is a maintenance task. Bumping the version in a pull request is ... I have no nice way to explain why that happens. We can just leave it at "it doesn't happen often"

But it happens, I also wouldn't do it ¯\_(ツ)_/¯, just a bold note in the `PR_TEMPLATE` (recommended) or in the linked dev guide shoud do the job

**Comment by d3viant0ne** [comment]
This is going to end up in the org docs. I'm going to stop working on defaults saturday and get the initial version pushed in webpack-contrib/organization and everyone can improve them from there.

**Comment by michael-ciniawsky** [comment]
Do you need the `RELEASE.md` from EWTP ?

**Comment by michael-ciniawsky** [comment]
We could add a `RELEASE.md` with a note about release management **if** we agree upon something like a weekly release day for major/minor/patch(non-critical) releases e.g every tuesday/thursday and so forth, but not really important and otherwise I think we can close the issue here :)
