### ISSUE TITLE
Generate an examples directory and run the examples on pre-push when testing?

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/webpack-defaults#32]
Currently it's easy to end up with false positives when testing. I.e. a loader might work against its tests but not webpack due to the runtime differences (different modules available). To avoid this, it would be a good idea to force projects to have at least one example that runs against webpack and uses loader/plugin there.

In ideal case it would run against multiple versions of webpack but even running against one would capture a whole category of errors.

**Comment by michael-ciniawsky** [comment]
I'm currently bundle the tests with webpack `target: node` and let them run after

```
file.js/file.json => webpack => file.test.js => jest
```

But coverage/error testing  is a problem I don't now how to solve atm 😛. Errors with LoaderRunner maybe, but haven't tried yet

**Comment by bebraw** [comment]
I set up **loader-runner** based tests [here](https://github.com/webpack-contrib/dynamic-css-loader). Even though it cuts some boilerplate and is good for testing loaders, it does not solve the problem. You are still running in Node context meaning modules like `fs` will be found. That's not true under webpack runtime.

This is more of an integration test level problem. Packages should have examples anyway to show their basic use cases so it makes sense to use them for validating that things work against webpack.

Taken further this would allow benchmarking against different versions of webpack but that's another problem better solved later and possibly through other means (separate service?).

**Comment by d3viant0ne** [comment]
I thought we solved the testing through webpack problem?

**Comment by bebraw** [comment]
Ok, time to close then.

It would be good to provide examples of initial tests if you run **webpack-defaults** the certain way but that's a separate problem.
