### ISSUE TITLE
Discuss: Multiple entrys/wrappers

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/webpack-defaults#47]
```bash
webpack-defaults --cjs index locals ...
```

```
|– lib
|  |– ... (Helpers)
|  |– index.js (Entry)
|  |– locals.js (Entry)
|– src 
|  |– ... (Helpers)
|  |– index.js (Entry)
|  |– locals.js (Entry)
|
|– index.js (Wrapper)
|– locals.js (Wrapper)
```

Loaders like `style-loader && css-loader` currently have multiple entries e.g

```js
// CSS 
{
   loader: 'css-loader', options: {}
}

// CSS Locals
{
   loader: 'css-loader/locals', options: {}
}
```

How could/should we support mutliple entries in `webpack-defaults` 😛

**Comment by bebraw** [comment]
The only way `'css-loader/locals'` can resolve through Node is that it points to a CommonJS module. That's the constraint here.

I think this means we have to agree on a convention. Maybe we'll get `locals.js` (CommonJS) and `locals.es6.js` (ES6, the other file resolves here) to work around this exception.

Or you can skip a convention and author using CommonJS module syntax (ES6+ otherwise). One less file then.

**Comment by d3viant0ne** [comment]
`./src/locals.js` contains the proxy.

`./src/lib/localsLoader.js` contains the lib.

Exactly how it is now except you need to `module.exports = require(”./lib/localsLoader”).default;`

**Comment by michael-ciniawsky** [comment]
Or `webpack-defaults` uses a CJS wrapper template and generates CJS wrappers for entries in './'

**template.js**
```js
import { writeFileSync } from 'fs'

export default (name) => writeFileSync('./', `module.exports = require('./lib/{name}').default`, 'utf8')
```

Are flags supported by `mrm` ? Writting by hand is also no problem here 😛 , but we need a convention for the how to, currently we set `"main": dist/cjs.js` in package.json, which to stay with the current convention would become e.g `css-loader/dist/locals[.cjs]`. Placing CJS wrapper(s) in the project root and switch to `main: 'index.js'` in package.json maybe easier

**Comment by d3viant0ne** [comment]
If you look at what all of those multiple entries are doing now, this is really a non-issue imo.

**Comment by michael-ciniawsky** [comment]
kk I will try it with `css-loader` today and maybe you're right 😛

**Comment by d3viant0ne** [comment]
I just tried it in css-loader, should work just fine. Have fun with the linting errors ..... ugh

**Comment by michael-ciniawsky** [comment]
mhmm...😩 and endure to preserve the current loader logic during style refactor

**Comment by michael-ciniawsky** [comment]
Yep sry this should be fine, I reopen in case it isn't :)
