### ISSUE TITLE
Test faster config for Jest on Travis

### ISSUE THREAD

**Issue by bebraw** [webpack-contrib/webpack-defaults#48]
Basic idea: `"test:ci": "jest --runInBand"`. Apparently running in the same process is faster on Travis but this needs verification.

**Comment by d3viant0ne** [comment]
It's faster on Circle, safe assumption it's going to be faster in Travis. All the hosted CI services run on containerized infrastructure with a single shared cpu thread.

If you run Jest default, the process does a ton of context switching that kills performance.
