### ISSUE TITLE
Babel: babel-preset-env

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/webpack-defaults#6]
Henry looks to be guiding Babel users over to env from using all the presets ( twitter discussion ) for Babel 7.

I've talked to him a bit about env & our requirements for Babel implementation, going to tinker with it this weekend & PR in an update assuming we can still cleanly achieve the same limited feature set using babel-preset-env over a custom built preset.

**Comment by bebraw** [comment]
Ok, cool. If that works, there would be less to maintain (engines definition?).

**Comment by d3viant0ne** [comment]
Yes and no. You still need to limit what is pulled in so instead up a big list of presets in a lib, you have a bunch of includes / excludes in a config.

That said, it's one less repo to maintain as it pushes the maintenance within the `webpack-defaults` repo.

**Comment by sapegin** [comment]
Sounds good!
