### ISSUE TITLE
Create consumable babel preset.

### ISSUE THREAD

**Issue by hulkish** [webpack-contrib/webpack-defaults#71]
So, here's what I'd like to do:

1. Create `src/babel-preset.js`.
2. Move the babel config itself from `src/tasks/babel.js` to `src/babel-preset.js`.
3. Update `src/tasks/babel.js` to use the new preset, aka:
```presets: ['webpack-defaults/dist/babel-preset']```
4. in addition, there are a few corrections to the usage of `babel-preset-env` config I'd like to apply.

Also, `babel-preset-env` does not include a few transforms that for example the `es2015` preset does include. For example: 

- `transform-object-rest-spread`
- `transform-class-properties` 
- `transform-export-extensions` (this one's not included in es2015 preset)

**Comment by michael-ciniawsky** [comment]
#72
