### ISSUE TITLE
Remove pre-commit

### ISSUE THREAD

**Issue by boopathi** [webpack-contrib/webpack-defaults#80]
I raised this concern in babili-webpack-plugin - https://github.com/webpack-contrib/babili-webpack-plugin/pull/51#discussion_r128243014. 

From that comment,

> Remove precommit?. I don't like packages changing my .git directory. git encourages to commit fast. I see this as an anti-pattern. We have a CI setup and I'd rather catch lint errors there when missed than use something which when INSTALLED changes stuff.

I think pre-commit shouldn't be a part of webpack-defaults or shouldn't be enforced on all projects.

**Comment by d3viant0ne** [comment]
`We run a standard set of boilerplate across all projects, without exception.`

If you want to commit something without validations, there is a git command for that but the pre-commit hook which exists to ensure clean commits was voted into the organization configuration and isn't going to be removed without being voted out ( highly unlikely )
