### ISSUE TITLE
feat: Drop custom eslint for Prettier

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/webpack-defaults#84]
This has been discussed via slack on more than one occasion. Prettier has the benefit of both excellent tooling integration as well as end an future debates about code style.

- [x] Update defaults to run gel with Prettier including the addition of `prettier-eslint`
- [x] Deprecate eslint-config-webpack
- [x] Include configs for all supported editors ( Sublime, Code, Atom, Vim? )

We may as well get this over with if only to limit the amount of rework for the remaining defaults conversions / incoming transfers.

Everything in the `2.0 milestone` should target https://github.com/webpack-contrib/webpack-defaults/tree/next

//cc @webpack-contrib/org-maintainers

**Comment by sapegin** [comment]
It’s not clear whether you want to remove ESLint entirely or just disable style rules.

**Comment by d3viant0ne** [comment]
I intend to deprecate `eslint-config-webpack` and replace it with Prettier & the eslint config that complements Prettier so they aren't stepping on each other.

Based on the feedback during conversions, the existing config is a bit restrictive in certain areas. So the end result is Prettier + prettier-eslint with the latter replacing the existing `eslint-config-webpack` as it pertains to this tool.

**Comment by michael-ciniawsky** [comment]
I personally think we still need `eslint-config-webpack` for [Code Quality Rules](https://github.com/prettier/prettier#how-does-it-compare-to-eslint-or-tslint-stylelint), but as @sapegin suggested, removed with all style related rules :)

**Comment by d3viant0ne** [comment]
Should have been more clear, we will base our style rules off of the config that works with prettier & then extend as we see fit taking into consideration some of the pain points people have highlighted during the first set of conversions to defaults.
