### ISSUE TITLE
RFC: CODEOWNERS

### ISSUE THREAD

**Issue by brutalcrozt** [webpack-contrib/webpack-defaults#85]
CODEOWNERS was introduced on [July 6, 2017](https://github.com/blog/2392-introducing-code-owners), more info at [github help](https://help.github.com/articles/about-codeowners/).

Suggesting to placed on `.github/CODEOWNERS`, related to [Cleaning House](https://github.com/webpack-contrib/organization/issues/5). Mainly aiming PR response time also correct reviewer.

I don't know how you organize files and process internally. But my basic idea just like this

```
# by extension
# .someext 

# single important file
# package.json @webpack-contrib/release-team

# by directory
# /test @webpack-contrib/test-team
# /docs @webpack-contrib/doc-team

```

Feel free to take over, or just let me know list file or directory and who is the **correct** owner. I will make the PR, when i got free time.

**Comment by d3viant0ne** [comment]
`@webpack-contrib/org-maintainers` would be the applicable team with a few limited libs that are managed by other teams or core members.

**Comment by bebraw** [comment]
Yup, this is a good idea. 👍

**Comment by michael-ciniawsky** [comment]
Yep, :+1: for managing reviews via `CODEOWNERS`

**Comment by evilebottnawi** [comment]
:+1:
