### ISSUE TITLE
Keep track of Commit Conventions

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack-contrib/webpack-defaults#93]
https://conventionalcommits.org/

This is more of a tracking issue for now as I saw discussion going on in `commitlint` && `standard-version` about slightly diverging from the Angular Team in the long-term to not rely on changes made by Angular in particular, which would be breaking for others. I update the issue with more info about this accordingly later :) (https://github.com/conventional-changelog/standard-version/pull/220)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky seems `@commitlint/config-conventional` is the most suitable for us. I vote :+1: for this feature.
